# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always
